export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'

export const SELECT_COMMUNITY = 'SELECT_COMMUNITY'
export const DELETE_COMMUNITY = 'DELETE_COMMUNITY'
export const LOAD_ALL_COMMUNITIES = 'LOAD_ALL_COMMUNITIES'
export const LOAD_COMMUNITY = 'LOAD_COMMUNITY'